import 'package:flutter/material.dart';

import 'package:combi_toys/theme/theme.dart';
import 'package:flutter/services.dart';

// https://www.coolors.co/2c2b2a-323130-efeeed-fcfbfa

ThemeData getDarkTheme({String accentColor='purple'}) {
  List<bool> useDarkTextOnAccent = [
    getContrastRatio(lightColor, accentColors[accentColor]![0]) <= getContrastRatio(darkColor, accentColors[accentColor]![0]),
    getContrastRatio(lightColor, accentColors[accentColor]![1]) <= getContrastRatio(darkColor, accentColors[accentColor]![1]),
    getContrastRatio(lightColor, accentColors[accentColor]![2]) <= getContrastRatio(darkColor, accentColors[accentColor]![2]),
    getContrastRatio(lightColor, accentColors[accentColor]![3]) <= getContrastRatio(darkColor, accentColors[accentColor]![3]),
  ];

  return ThemeData(
    // brightness: Brightness.dark,
    // useMaterial3: true,
    // adaptations: ,
    // applyElevationOverlayColor: ,
    // cupertinoOverrideTheme: ,
    // extensions: ,
    // inputDecorationTheme: ,
    // materialTapTargetSize: ,
    // pageTransitionsTheme: ,
    // platform: ,
    scrollbarTheme: ScrollbarThemeData(),
    // splashFactory: ,
    useMaterial3: true,
    // useSystemColors: ,
    // visualDensity: ,
    colorScheme: ColorScheme.dark(
      primary: accentColors[accentColor]![2],
      onPrimary: useDarkTextOnAccent[2]?darkColor:lightColor,
      primaryContainer: accentColors[accentColor]![3],
      onPrimaryContainer: accentColors[accentColor]![0],
      primaryFixed: accentColors[accentColor]![3],
      primaryFixedDim: accentColors[accentColor]![2],
      onPrimaryFixed: accentColors[accentColor]![0],
      onPrimaryFixedVariant: useDarkTextOnAccent[2]?darkColor:lightColor,
      secondary: accentColors[accentColor]![2],                                 // same as primary
      onSecondary: useDarkTextOnAccent[2]?darkColor:lightColor,
      secondaryContainer: accentColors[accentColor]![3],
      onSecondaryContainer: accentColors[accentColor]![0],
      secondaryFixed: accentColors[accentColor]![3],
      secondaryFixedDim: accentColors[accentColor]![2],
      onSecondaryFixed: accentColors[accentColor]![0],
      onSecondaryFixedVariant: useDarkTextOnAccent[2]?darkColor:lightColor,
      tertiary: accentColors[accentColor]![2],                                  // same as primary
      onTertiary: useDarkTextOnAccent[2]?darkColor:lightColor,
      tertiaryContainer: accentColors[accentColor]![3],
      onTertiaryContainer: accentColors[accentColor]![0],
      tertiaryFixed: accentColors[accentColor]![3],
      tertiaryFixedDim: accentColors[accentColor]![2],
      onTertiaryFixed: accentColors[accentColor]![0],
      onTertiaryFixedVariant: useDarkTextOnAccent[2]?darkColor:lightColor,
      error: accentColors['red']![2],
      onError: darkColor,
      errorContainer: accentColors['red']![3],
      onErrorContainer: accentColors['red']![0],
      surface: darkColor,
      onSurface: lightColor,
      surfaceDim: darkColor,
      surfaceBright: Color.lerp(darkColor, lightAccentColor, 0.25),
      surfaceContainerLowest: Color.lerp(darkColor, darkAccentColor, 0.5),
      surfaceContainerLow: Color.lerp(darkColor, darkAccentColor, 0.25),
      surfaceContainer: darkColor,
      surfaceContainerHigh: Color.lerp(darkColor, lightAccentColor, 0.125),
      surfaceContainerHighest: Color.lerp(darkColor, lightAccentColor, 0.25),
      onSurfaceVariant: lightColor,
      outline: darkAccentColor,
      outlineVariant: lightAccentColor.withAlpha(128),
      shadow: darkAccentColor,
      scrim: darkAccentColor,
      inverseSurface: lightColor,
      onInverseSurface: darkColor,
      inversePrimary: accentColors[accentColor]![1],
      surfaceTint: Colors.transparent,
    ),
    brightness: Brightness.dark,
    // colorSchemeSeed: ,
    // canvasColor: ,
    // cardColor: ,
    // disabledColor: ,
    // dividerColor: darkAccentColor,
    // focusColor: ,
    // highlightColor: ,
    // hintColor: ,
    // hoverColor: ,
    // primaryColor: ,
    // primaryColorDark: ,
    // primaryColorLight: ,
    // primarySwatch: ,
    // scaffoldBackgroundColor: ,
    // secondaryHeaderColor: ,
    // shadowColor: ,
    // splashColor: ,
    // unselectedWidgetColor: ,
    // fontFamily: ,
    // fontFamilyFallback: ,
    // package: ,
    iconTheme: IconThemeData(
      // color: lightColor,
    ),
    // primaryIconTheme: ,
    // primaryTextTheme: ,
    // textTheme: ,
    // typography: ,
    // actionIconTheme: ,
    appBarTheme: AppBarThemeData(
      foregroundColor: useDarkTextOnAccent[2]?darkColor:lightColor,
      backgroundColor: accentColors[accentColor]![2],
      elevation: 5,
      scrolledUnderElevation: 5,
      shadowColor: darkAccentColor,
      shape: AppBarShape(17122003),
      // toolbarHeight: ,
      // TODO: this needs to be checked on a mobile device
      systemOverlayStyle: SystemUiOverlayStyle(
        systemNavigationBarColor: accentColors[accentColor]![2],
        systemNavigationBarDividerColor: useDarkTextOnAccent[2]?darkColor:lightColor,
        systemNavigationBarIconBrightness: useDarkTextOnAccent[2]?Brightness.dark:Brightness.light,
        systemNavigationBarContrastEnforced: false,
        statusBarColor: accentColors[accentColor]![2],
        statusBarBrightness: Brightness.dark,
        statusBarIconBrightness: useDarkTextOnAccent[2]?Brightness.dark:Brightness.light,
        systemStatusBarContrastEnforced: false,
      ),
    ),
    // badgeTheme: ,
    // bannerTheme: ,
    bottomAppBarTheme: BottomAppBarThemeData(
      color: accentColors[accentColor]![0],
      elevation: 5,
      // TODO: define custom notched shape
      // shape: ,
      surfaceTintColor: null,
      shadowColor: darkAccentColor,
    ),
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      backgroundColor: accentColors[accentColor]![0],
      elevation: 5,
      selectedItemColor: useDarkTextOnAccent[0]?darkColor:lightColor,
      unselectedItemColor: accentColors[accentColor]![3],
    ),
    // bottomSheetTheme: ,
    // buttonTheme: , // TODO: seems to not be working
    cardTheme: CardThemeData(
      clipBehavior: Clip.antiAlias,
      shadowColor: darkAccentColor,
      surfaceTintColor: Colors.transparent,
      elevation: 3,
      // TODO: use custom rounded rectangle shape
      // shape: ,
    ),
    // carouselViewTheme: ,
    // checkboxTheme: ,
    // chipTheme: ,
    // dataTableTheme: ,
    // datePickerTheme: ,
    // dialogTheme: ,
    // dividerTheme: ,
    // drawerTheme: ,
    // dropdownMenuTheme: ,
    // elevatedButtonTheme: ,
    // expansionTileTheme: ,
    // filledButtonTheme: ,
    floatingActionButtonTheme: FloatingActionButtonThemeData(
      foregroundColor: useDarkTextOnAccent[1]?darkColor:lightColor,
      backgroundColor: accentColors[accentColor]![1],
      focusColor: accentColors[accentColor]![2],
      hoverColor: accentColors[accentColor]![2].withAlpha(128),
      splashColor: accentColors[accentColor]![2],
      elevation: 5,
      focusElevation: 10,
      hoverElevation: 10,
      disabledElevation: 0,
      highlightElevation: 7,
      // TODO: define custom rounded rectangle shape
      // shape: ,
    ),
    // iconButtonTheme: ,
    // listTileTheme: ,
    // menuBarTheme: ,
    // menuButtonTheme: ,
    // menuTheme: ,
    // navigationBarTheme: ,
    // navigationDrawerTheme: ,
    // navigationRailTheme: ,
    // outlinedButtonTheme: ,
    // popupMenuTheme: ,
    // progressIndicatorTheme: ,
    // radioTheme: ,
    // searchBarTheme: ,
    // searchViewTheme: ,
    // segmentedButtonTheme: ,
    // sliderTheme: ,
    // snackBarTheme: ,
    // switchTheme: ,
    // tabBarTheme: ,
    // textButtonTheme: ,
    // textSelectionTheme: ,
    // timePickerTheme: ,
    // toggleButtonsTheme: ,
    // tooltipTheme: ,

    // buttonBarTheme: ,
    // dialogBackgroundColor: ,
    // indicatorColor: ,
  );
}
