# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: FLutter Web Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Optional: Verify formatting (uncomment if you want to enforce formatting)
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
      
      # Optional: Run tests (uncomment if you have tests)
      # - name: Run tests
      #   run: flutter test

      - name: Build web app
        run: flutter build web --release --base-href /CombiToys/

      - name: Upload build artifacts # for deployment
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Downloaf build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-release
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          
